name: Desplegar Frontend en GitHub Pages

on:
  push:
    branches:
      - main

# Otorga permisos
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Descarga el c√≥digo
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Configura GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # 3. Sube el artefacto (en github pages solo se carga el frontend ya que el repositorio del backend es render)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend

      # 4. Despliega en GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
